#jdbc:
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbc:myql://47.105.193.129:3306/practice
#  username: root
#  password: 123456

server:
  port: 80


# 激活yaml配置文件
spring:
  profiles:
    active: dev,prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:myql://47.105.193.129:3306/test?useSSL=false&serverTimezone=UTC;
    hikari:
      maximumPoolSize: 100


# 日志记录级别
logging:
  level:
    com.janlei: debug
    org.springframework: info

# mybatis
mybatis:
  # 实体别名路径
  type-aliases-package: com.janlei.model.entity
  # mapper映射文件路径
  mapper-locations: classpath:mapper/*.xml
  # 日志实现
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
