jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:myql://47.105.193.129:3306/practice
  username: root
  password: 123456

server:
  port: 80


# 激活yaml配置文件
spring:
  profiles:
    active: dev,prod